Ogre Procedural: Procedural::Utils Class Reference
Procedural::Utils Class Reference
Holds a bunch of static utility functions.
#include <ProceduralUtils.h>
Static Public Member Functions
static void log (const Ogre::String &st)
Outputs something to the ogre log, with a [PROCEDURAL] prefix.
static Ogre::Vector3 min (const Ogre::Vector3 &v1, const Ogre::Vector3 &v2)
Gets the min of the coordinates between 2 vectors.
static Ogre::Vector3 max (const Ogre::Vector3 &v1, const Ogre::Vector3 &v2)
Gets the max of the coordinates between 2 vectors.
static Ogre::Vector2 min (const Ogre::Vector2 &v1, const Ogre::Vector2 &v2)
Gets the min of the coordinates between 2 vectors.
static Ogre::Vector2 max (const Ogre::Vector2 &v1, const Ogre::Vector2 &v2)
Gets the max of the coordinates between 2 vectors.
static Ogre::AxisAlignedBox AABBfromPoints (std::vector< Ogre::Vector3 > points)
Builds an AABB from a list of points.
static std::string getName (const std::string &prefix="default")
Generate a name from a prefix and a counter.
static Ogre::Vector3 vectorPermute (const Ogre::Vector3 &in)
Shifts the components of the vector to the right.
static Ogre::Vector3 vectorAntiPermute (const Ogre::Vector3 &in)
Shifts the components of the vector to the left.
static Ogre::Vector2 rotateVector2 (const Ogre::Vector2 &in, Ogre::Radian angle)
static int cap (int n, int min, int max)
Caps n between min and max.
static int modulo (int n, int cap)
An extend version of the standard modulo, in that int values are "wrapped" in both directions, whereas with standard modulo, (-1)%2 == -1 Always return an int between 0 and cap-1.
static Ogre::Radian angleBetween (const Ogre::Vector2 &v1, const Ogre::Vector2 &v2)
Equivalent of Ogre::Vector3::angleBetween, applied to Ogre::Vector2.
static Ogre::Radian angleTo (const Ogre::Vector2 &v1, const Ogre::Vector2 &v2)
Gives the oriented angle from v1 to v2 in the [0;2PI[ range.
static Ogre::Radian signedAngleTo (const Ogre::Vector2 &v1, const Ogre::Vector2 &v2)
Gives the oriented angle from v1 to v2 in the ]-PI;PI] range.
static Ogre::Quaternion _computeQuaternion (const Ogre::Vector3 &direction, const Ogre::Vector3 &upVector=Ogre::Vector3::UNIT_Y)
Computes a quaternion between UNIT_Z and direction.
static Ogre::Vector3 vec2ToVec3Y (const Ogre::Vector2 &pos)
Maps a vector2 to vector3, with Y=0.
static unsigned int binom (unsigned int a, unsigned int b)
binomial coefficients (a over b)
static Ogre::Vector2 reframe (const Ogre::RealRect &rect, const Ogre::Vector2 &input)
Transforms an input vector expressed in the 0,0->1,1 rect towards another rect.
Detailed Description
Holds a bunch of static utility functions.
Member Function Documentation
static Ogre::Quaternion Procedural::Utils::_computeQuaternion (const Ogre::Vector3 & direction, const Ogre::Vector3 & upVector = Ogre::Vector3::UNIT_Y) static
Computes a quaternion between UNIT_Z and direction.
It keeps the "up" vector to UNIT_Y
static Ogre::AxisAlignedBox Procedural::Utils::AABBfromPoints (std::vector< Ogre::Vector3 > points) static
Builds an AABB from a list of points.
References Ogre::AxisAlignedBox::getMaximum(), Ogre::AxisAlignedBox::getMinimum(), getName(), Ogre::AxisAlignedBox::setMaximum(), and Ogre::AxisAlignedBox::setMinimum().
static Ogre::Radian Procedural::Utils::angleBetween (const Ogre::Vector2 & v1, const Ogre::Vector2 & v2) static
Equivalent of Ogre::Vector3::angleBetween, applied to Ogre::Vector2.
References Ogre::Math::ACos(), Ogre::Math::Clamp(), Ogre::Vector2::dotProduct(), and Ogre::Vector2::length().
static Ogre::Radian Procedural::Utils::angleTo (const Ogre::Vector2 & v1, const Ogre::Vector2 & v2) static
Gives the oriented angle from v1 to v2 in the [0;2PI[ range.
References Ogre::Vector2::crossProduct(), and Ogre::Math::TWO_PI.
static unsigned int Procedural::Utils::binom (unsigned int a, unsigned int b) static
binomial coefficients (a over b)
static int Procedural::Utils::cap (int n, int min, int max) static
Caps n between min and max.
Referenced by Procedural::Shape::getBoundedIndex(), Procedural::Path::getPoint(), Procedural::CatmullRomSpline3::safeGetPoint(), Procedural::CubicHermiteSpline2::safeGetPoint(), Procedural::CatmullRomSpline2::safeGetPoint(), Procedural::CubicHermiteSpline3::safeGetPoint(), Procedural::KochanekBartelsSpline2::safeGetPoint(), Procedural::RoundedCornerSpline3::safeGetPoint(), Procedural::BezierCurve3::safeGetPoint(), Procedural::RoundedCornerSpline2::safeGetPoint(), and Procedural::BezierCurve2::safeGetPoint().
static std::string Procedural::Utils::getName (const std::string & prefix = "default") static
Generate a name from a prefix and a counter.
Referenced by Procedural::MeshGenerator< TorusGenerator >::realizeMesh().
static void Procedural::Utils::log (const Ogre::String & st) static
Outputs something to the ogre log, with a [PROCEDURAL] prefix.
static Ogre::Vector3 Procedural::Utils::max (const Ogre::Vector3 & v1, const Ogre::Vector3 & v2) static
Gets the max of the coordinates between 2 vectors.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
static Ogre::Vector2 Procedural::Utils::max (const Ogre::Vector2 & v1, const Ogre::Vector2 & v2) static
Gets the max of the coordinates between 2 vectors.
References Ogre::Vector2::x, and Ogre::Vector2::y.
static Ogre::Vector3 Procedural::Utils::min (const Ogre::Vector3 & v1, const Ogre::Vector3 & v2) static
Gets the min of the coordinates between 2 vectors.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
static Ogre::Vector2 Procedural::Utils::min (const Ogre::Vector2 & v1, const Ogre::Vector2 & v2) static
Gets the min of the coordinates between 2 vectors.
References Ogre::Vector2::x, and Ogre::Vector2::y.
static int Procedural::Utils::modulo (int n, int cap) static
An extend version of the standard modulo, in that int values are "wrapped" in both directions, whereas with standard modulo, (-1)%2 == -1 Always return an int between 0 and cap-1.
Referenced by Procedural::Shape::getBoundedIndex(), Procedural::Path::getPoint(), Procedural::CatmullRomSpline3::safeGetPoint(), Procedural::CubicHermiteSpline2::safeGetPoint(), Procedural::CatmullRomSpline2::safeGetPoint(), Procedural::CubicHermiteSpline3::safeGetPoint(), Procedural::KochanekBartelsSpline2::safeGetPoint(), Procedural::RoundedCornerSpline3::safeGetPoint(), Procedural::BezierCurve3::safeGetPoint(), Procedural::RoundedCornerSpline2::safeGetPoint(), and Procedural::BezierCurve2::safeGetPoint().
static Ogre::Vector2 Procedural::Utils::reframe (const Ogre::RealRect & rect, const Ogre::Vector2 & input) static
Transforms an input vector expressed in the 0,0->1,1 rect towards another rect.
References TRect< Real >::height(), TRect< Real >::left, TRect< Real >::top, TRect< Real >::width(), Ogre::Vector2::x, and Ogre::Vector2::y.
static Ogre::Vector2 Procedural::Utils::rotateVector2 (const Ogre::Vector2 & in, Ogre::Radian angle) static
References Ogre::Math::Cos(), Ogre::Math::Sin(), Ogre::Vector2::x, and Ogre::Vector2::y.
static Ogre::Radian Procedural::Utils::signedAngleTo (const Ogre::Vector2 & v1, const Ogre::Vector2 & v2) static
Gives the oriented angle from v1 to v2 in the ]-PI;PI] range.
References Ogre::Vector2::crossProduct(), and Ogre::Vector3::UNIT_Y.
static Ogre::Vector3 Procedural::Utils::vec2ToVec3Y (const Ogre::Vector2 & pos) static
Maps a vector2 to vector3, with Y=0.
References Ogre::Vector2::x, and Ogre::Vector2::y.
static Ogre::Vector3 Procedural::Utils::vectorAntiPermute (const Ogre::Vector3 & in) static
Shifts the components of the vector to the left.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
static Ogre::Vector3 Procedural::Utils::vectorPermute (const Ogre::Vector3 & in) static
Shifts the components of the vector to the right.
References Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
The documentation for this class was generated from the following file:
ProceduralUtils.h