Ogre Procedural: Procedural::Sharpen Class Reference
Procedural::Sharpen Class Reference
Textures
Increase sharpness on input image.
#include <ProceduralTextureModifiers.h>
Public Types
enum SHARP_TYPE { SHARP_BASIC, SHARP_GAUSSIAN }
List of algorithms to blur.
Public Member Functions
Sharpen (TextureBufferPtr pBuffer)
Default constructor.
Sharpen & setSize (Ogre::uchar size)
Set the gaussian block size.
Sharpen & setSigma (Ogre::uchar sigma)
Set sigma constant for gaussian filter.
Sharpen & setType (SHARP_TYPE type)
Set the algorithm to sharp.
TextureBufferPtr process ()
Run image manipulation.
Ogre::String getName ()
Get name of the filter as string.
void setLog (bool enable=true)
Enable/Disable logging.
Protected Member Functions
void logMsg (Ogre::String msg)
Protected Attributes
TextureBufferPtr mBuffer
Ogre::String mName
bool mLog
Detailed Description
Increase sharpness on input image.
Sharp the input image by a specified algorithm.
Examples: SHARP_BASIC
Procedural::TextureBuffer bufferImage(256);
Procedural::Image(&bufferImage).setFile("red_brick.jpg").process();
Procedural::Sharpen(&bufferImage).setType(Procedural::Sharpen::SHARP_BASIC).process();
SHARP_GAUSSIAN
Procedural::TextureBuffer bufferImage(256);
Procedural::Image(&bufferImage).setFile("red_brick.jpg").process();
Procedural::Sharpen(&bufferImage).setType(Procedural::Sharpen::SHARP_GAUSSIAN).process();
Member Enumeration Documentation
enum Procedural::Sharpen::SHARP_TYPE
List of algorithms to blur.
Enumerator
SHARP_BASIC
Use simplified block filter to sharp.
SHARP_GAUSSIAN
Use gaussian filter to sharp.
Constructor & Destructor Documentation
Procedural::Sharpen::Sharpen (TextureBufferPtr pBuffer)
Default constructor.
Parameters
pBuffer Image buffer where to modify the image.
References Ogre::ColourValue::Black, Procedural::TextureBuffer::getHeight(), Procedural::TextureBuffer::getWidth(), setPosition(), and type.
Member Function Documentation
Ogre::String Procedural::TextureProcessing::getName () inherited
Get name of the filter as string.
void Procedural::TextureProcessing::logMsg (Ogre::String msg) protected inherited
TextureBufferPtr Procedural::Sharpen::process () virtual
Run image manipulation.
Returns
Pointer to image buffer which has been set in the constructor.
Implements Procedural::TextureProcessing.
void Procedural::TextureProcessing::setLog (bool enable = true) inherited
Enable/Disable logging.
Parameters
enable true enables logging of filter actions
Sharpen& Procedural::Sharpen::setSigma (Ogre::uchar sigma)
Set sigma constant for gaussian filter.
Parameters
sigma New sigma constant for gaussian sharp filter [0, 255] (default 92)
Sharpen& Procedural::Sharpen::setSize (Ogre::uchar size)
Set the gaussian block size.
Parameters
size New block size for gaussian sharp filter [3, 255] (default 5)
Sharpen& Procedural::Sharpen::setType (SHARP_TYPE type)
Set the algorithm to sharp.
Parameters
type New algorithm to sharp (default SHARP_BASIC)
Member Data Documentation
TextureBufferPtr Procedural::TextureProcessing::mBuffer protected inherited
bool Procedural::TextureProcessing::mLog protected inherited
Ogre::String Procedural::TextureProcessing::mName protected inherited
The documentation for this class was generated from the following file:
ProceduralTextureModifiers.h